"""Small calibration assembler. Syntax: FADD F0,F1,F2; BR.2 label.

Modes are explicit numeric suffixes; addresses use base register + word offset:
LD F0,A1,3. Labels and # comments are supported. ROM/header are generated from
the same ISA, and no host-dependent absolute paths enter the generated output.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
ISA = json.loads((ROOT / 'data/programs/calibration/isa.json').read_text())


def assemble(source, capacity=2048):
    labels, lines = {}, []
    for number, raw in enumerate(source.splitlines(), 1):
        text = raw.split('#', 1)[0].strip()
        if ':' in text:
            label, text = text.split(':', 1)
            label, text = label.strip(), text.strip()
            if not re.fullmatch(r'[A-Za-z_]\w*', label) or label in labels:
                raise ValueError(f'line {number}: invalid/duplicate label {label}')
            labels[label] = len(lines)
        if text:
            lines.append((number, text))
    if not lines or len(lines) > capacity:
        raise ValueError('empty program or ROM capacity exceeded')
    words = []
    for pc, (number, text) in enumerate(lines):
        try:
            head, *tail = text.split(None, 1)
            name, *suffix = head.upper().split('.')
            opcode, signature, modes = ISA['instructions'][name]
            mode = int(suffix[0]) if suffix else 0
            if len(suffix) > 1 or mode not in modes:
                raise ValueError('unsupported mode')
            operands = [t.strip() for t in tail[0].split(',')] if tail else []
            specs = signature.split(',') if signature else []
            if len(specs) != len(operands):
                raise ValueError(f'expected operands: {signature}')
            fields = dict(opcode=opcode, mode=mode, rd=0, ra=0, rb=0, imm=0)
            for spec, value in zip(specs, operands):
                if spec[0] in 'AF':
                    if not re.fullmatch(spec[0] + '[0-7]', value.upper()):
                        raise ValueError(f'invalid {spec[0]} register {value}')
                    fields['r' + spec[1]] = int(value[1])
                else:
                    n = labels[value] - pc - 1 if spec == 'rel' and value in labels else int(value, 0)
                    bits = 14 if spec == 'rel' else int(spec[1:])
                    signed = spec in ('rel', 's14')
                    lo, hi = (-(1 << (bits-1)), (1 << (bits-1))-1) if signed else (0, (1 << bits)-1)
                    if not lo <= n <= hi:
                        raise ValueError(f'operand outside {spec}: {n}')
                    if spec == 'rel' and not 0 <= pc + 1 + n < len(lines):
                        raise ValueError('branch target outside program')
                    if name == 'KEXEC' and n > 4:
                        raise ValueError('undefined kernel')
                    fields['imm'] = n & 0x3fff
            words.append(sum(fields[k] << offset for k, (offset, width) in ISA['fields'].items()))
        except (KeyError, ValueError) as exc:
            raise ValueError(f'line {number} ({text}): {exc}') from exc
    return words, labels


def header():
    result = ['// Generated by scripts/calibration/engine/assemble.py; edit isa.json.',
              '`ifndef CALIB_ENGINE_DEFS_VH', '`define CALIB_ENGINE_DEFS_VH']
    for name, (code, signature, modes) in ISA['instructions'].items():
        result.append(f"`define CE_{name} 6'h{code:02x}")
    result += ['`endif', '']
    return '\n'.join(result)


def legality_function():
    # Included inside the sequencer. Reserved fields and modes are checked in
    # hardware too, rather than relying on a trusted assembler for safety.
    out = ['// Generated from isa.json.', 'function ce_legal;',
           ' input [31:0] instruction;', ' begin', '  case(instruction[31:26])']
    for name, (code, signature, modes) in ISA['instructions'].items():
        allowed = 0xfc000000
        if modes != [0]:
            allowed |= 7 << 23
        for spec in signature.split(',') if signature else []:
            if spec[0] in 'AF':
                offset, width = ISA['fields']['r' + spec[1]]
                allowed |= ((1 << width)-1) << offset
            else:
                allowed |= (1 << (14 if spec == 'rel' else int(spec[1:]))) - 1
        mode_expr = ' || '.join(f"instruction[25:23]==3'd{m}" for m in modes)
        kernel = " && instruction[13:0]<=14'd4" if name == 'KEXEC' else ''
        out.append(f"  `CE_{name}:ce_legal=((instruction & 32'h{(~allowed)&0xffffffff:08x})==0) && ({mode_expr}){kernel};")
    out += ['  default:ce_legal=0;', '  endcase', ' end', 'endfunction', '']
    return '\n'.join(out)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path, nargs='?')
    parser.add_argument('--out', type=Path, default=ROOT/'build/calibration_engine')
    parser.add_argument('--headers', action='store_true')
    args = parser.parse_args()
    if args.headers:
        (ROOT/'rtl/include/calib_engine_defs.vh').write_text(header(), encoding='utf-8')
        (ROOT/'rtl/include/calib_engine_decode.vh').write_text(legality_function(), encoding='utf-8')
    if args.source:
        words, labels = assemble(args.source.read_text(encoding='utf-8'))
        args.out.mkdir(parents=True, exist_ok=True)
        (args.out/(args.source.stem+'.mem')).write_text(''.join(f'{v:08x}\n' for v in words), encoding='ascii')
        (args.out/(args.source.stem+'.json')).write_text(json.dumps(dict(words=len(words),labels=labels),indent=2))
        print(f'{args.source.name}: {len(words)} instructions')
