"""Build tracked ROM initialization from assembly; no runtime absolute paths.

The checked-in generated include lets PDS/ModelSim compile after a clone,
without a Python prerequisite or a copied ROM in a vendor task directory.
"""
from assemble import ROOT,assemble

def pose_rom():
    source='\n'.join((ROOT/'data/programs/calibration'/name).read_text(encoding='utf-8')
                     for name in ('pose.asm','rotation_inverse.asm'))
    words,labels=assemble(source,1024)
    lines=['// Generated from pose.asm + rotation_inverse.asm by build_rom.py.']
    lines += [f"program_memory[{i}]=32'h{w:08x};" for i,w in enumerate(words)]
    (ROOT/'rtl/include/pose_program_init.vh').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    (ROOT/'rtl/include/pose_program_defs.vh').write_text(
        '// Generated by build_rom.py.\n'+f'`define POSE_PROGRAM_WORDS {len(words)}\n'+
        f"`define POSE_COMMON_PC {labels['pose_common']}\n`define POSE_VIEW_PC {labels['pose_view']}\n",encoding='utf-8')
    print(f'pose ROM: {len(words)} words, view entry {labels["pose_view"]}')

def combined_rom():
    from build_lm import build
    from build_validate import build as build_validate
    from build_init import build as build_init
    pose_rom();lm,_=build()
    validation,_=build_validate()
    initialization,_=build_init()
    entries={'LM':0,'VALIDATE':len(lm),'INIT':len(lm)+len(validation)}
    words=lm+validation+initialization
    assert len(words)<=4096
    padded=words+[0x040000e1]*(4096-len(words))
    (ROOT/'rtl/include/calibration_program_init.vh').write_text(
        '// Generated by build_rom.py: shared LM, validation and initialization.\n'+
        '\n'.join(f"program_memory[{i}]=32'h{w:08x};" for i,w in enumerate(padded))+'\n',encoding='utf-8')
    (ROOT/'rtl/include/calibration_program_defs.vh').write_text(
        '// Generated by build_rom.py.\n'+f'`define CALIBRATION_PROGRAM_WORDS {len(words)}\n'+
        ''.join(f'`define {name}_ENGINE_PC {pc}\n' for name,pc in entries.items()),encoding='utf-8')
    return entries

if __name__=='__main__':combined_rom()
