"""FP64 tensor solve + coordinate update + convergence, one shared scalar ALU."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def build():
    words=[];listing=[];labels={};fix=[]
    def fp(op,d,a,b=16):
        words.append((op<<23)|(d<<19)|(a<<14)|(b<<9));listing.append(f'FP {op} r{d},r{a},r{b}')
    def branch(name,condition):
        fix.append((len(words),name));words.append((2<<28)|condition);listing.append(f'BR {condition} {name}')
    def out(a,which):words.append((1<<28)|(a<<14)|which);listing.append(f'OUT {which},r{a}')
    def end(ok):words.append((3<<28)|ok);listing.append(f'END {ok}')
    def label(name):labels[name]=len(words);listing.append(name+':')
    fp(2,7,0,2);fp(2,8,1,1);fp(1,9,7,8);fp(0,10,0,2)
    fp(2,7,17,10);fp(2,7,7,10)
    fp(13,0,10,18);branch('reject',1)
    fp(13,0,9,7);branch('reject',2)
    fp(2,7,2,3);fp(2,8,1,4);fp(1,7,7,8);fp(3,11,7,9)
    fp(2,7,0,4);fp(2,8,1,3);fp(1,7,7,8);fp(3,12,7,9)
    out(11,0);out(12,1);branch('accept',3)
    fp(11,5,5);fp(11,6,6)
    fp(0,13,5,11);fp(12,13,13)
    fp(0,14,6,12);fp(12,14,14)
    fp(2,7,11,11);fp(2,8,12,12);fp(0,15,7,8)
    out(13,2);out(14,3);out(15,4)
    label('accept');end(1)
    label('reject');end(0)
    for i,name in fix:words[i]|=labels[name]<<8
    assert len(words)<=64
    (ROOT/'rtl/include/feature_program_init.vh').write_text(
        '// Generated by scripts/compute/microcode/build_feature.py\n'+
        '\n'.join(f"program_rom[{i}]=32'h{v:08x};" for i,v in enumerate(words))+'\n')
    outdir=ROOT/'data/programs/features';outdir.mkdir(parents=True,exist_ok=True)
    (outdir/'refine.lst').write_text('\n'.join(listing)+'\n')
    print(f'Feature program: {len(words)} x 32 bits')
if __name__=='__main__':build()
