"""Assemble exact Q128 scalar math programs into portable Verilog ROM init.

32-bit words: op[31:26], dst[25:22], srcA[21:14], srcB[13:6], mode[5:0].
Branches use low 14 bits as absolute ROM target. SETI uses increment[21:16],
limit[15:8], initial[7:0]. Register addresses 0..15 are writable; constants
occupy 16..127 and the CORDIC angle table 128..255. No generic CPU software.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
OPS=dict(RET=0,MOV=1,ADD=2,SUB=3,NEG=4,SAR=5,SHL=6,MULQ=7,MULI=8,
         DIVQ=9,DIVI=10,FP=11,FROMFP=12,UNPACK=13,SETSCALE=14,GETSCALE=15,
         SETI=16,GETI=17,LOOP=18,BR=19,RANGE=20,ATEST=21,ANGLE=22,
         TEST=23,ADDC=24,SUBC=25,SELECT=26)
ZERO,ONE,LN2,HALFPI,PI,GAIN,HLN2,FONE,FTWO,FTHREE,I32=range(16,27)

def build():
    code=[];labels={};fixups=[];listing=[]
    def label(name):labels[name]=len(code);listing.append(name+':')
    def emit(op,d=0,a=0,b=0,m=0):
        code.append((OPS[op]<<26)|(d<<22)|(a<<14)|(b<<6)|m)
        listing.append(f'  {op:8} {d}, {a}, {b}, {m}')
    def branch(name,condition=0,a=0):
        fixups.append((len(code),name));emit('BR',condition,a)
    def loop(name):fixups.append((len(code),name));emit('LOOP')
    def iterations(first,last,step):
        code.append((OPS['SETI']<<26)|(step<<16)|(last<<8)|first)
        listing.append(f'  SETI     {first}, {last}, {step}')
    def fp(d,a,b,op):emit('FP',d,a,b,op)
    def ret(a,mode=0):emit('RET',a=a,m=mode)

    label('exp')
    emit('FROMFP',2,0);emit('MOV',3,2)
    branch('exp_negative',1,2)
    emit('ADD',3,3,HLN2);branch('exp_reduce')
    label('exp_negative');emit('SUB',3,3,HLN2)
    label('exp_reduce');emit('DIVI',3,3,LN2);emit('SETSCALE',a=3)
    emit('MULI',4,3,LN2);emit('SUB',2,2,4)
    emit('MOV',3,ONE);emit('MOV',4,ONE);iterations(1,32,1)
    label('exp_loop');emit('MULQ',3,3,2);emit('GETI',5)
    emit('DIVI',3,3,5);emit('ADD',4,4,3);loop('exp_loop');ret(4,1)

    label('log');emit('UNPACK',2,0);emit('GETSCALE',6)
    emit('SUB',3,2,ONE);emit('ADD',4,2,ONE);emit('DIVQ',2,3,4)
    emit('MULQ',3,2,2);emit('MOV',4,2);emit('MOV',5,2);iterations(3,79,2)
    label('log_loop');emit('MULQ',4,4,3);emit('GETI',7)
    emit('DIVI',7,4,7);emit('ADD',5,5,7);loop('log_loop')
    emit('MULI',6,6,LN2);emit('SHL',5,5);emit('ADD',5,5,6)
    emit('SETSCALE',a=ZERO);ret(5,1)
    label('log_near')
    fp(2,0,FONE,1);fp(3,0,FONE,0);fp(2,2,3,3)
    fp(3,2,2,2);fp(3,3,2,2);fp(3,3,FTHREE,3)
    fp(3,2,3,0);fp(3,3,FTWO,2);ret(3)

    label('trig');emit('RANGE',2,0);emit('MULQ',2,2,HALFPI)
    emit('MOV',0,GAIN);emit('MOV',1,ZERO);iterations(0,127,1)
    label('rotate')
    emit('TEST',a=2,m=0);emit('SAR',3,1,m=1);emit('SAR',4,0,m=1);emit('ANGLE',5)
    emit('SUBC',0,0,3);emit('ADDC',1,1,4);emit('SUBC',2,2,5);loop('rotate')
    emit('SELECT',2,0,1);emit('SETSCALE',a=ZERO);ret(2,1)

    label('acos')
    fp(2,FONE,0,1);fp(3,FONE,0,0);fp(2,2,3,2);fp(2,2,ZERO,4)
    emit('MOV',1,0);emit('MOV',0,2)
    label('atan')
    emit('ATEST',a=0,b=1)
    emit('UNPACK',2,0);emit('GETSCALE',4)
    emit('UNPACK',3,1);emit('GETSCALE',5);emit('SUB',6,4,5)
    branch('atan_align',7)
    emit('ADD',7,6,I32);branch('atan_small',1,7)
    label('atan_align');branch('atan_y_small',1,6)
    emit('SAR',3,3,6);branch('atan_aligned')
    label('atan_y_small');emit('NEG',6,6);emit('SAR',2,2,6)
    label('atan_aligned');emit('MOV',0,3);emit('MOV',1,2);emit('MOV',2,ZERO)
    iterations(0,127,1)
    label('vector')
    emit('TEST',a=1,m=1);emit('SAR',3,1,m=1);emit('SAR',4,0,m=1);emit('ANGLE',5)
    emit('ADDC',0,0,3);emit('SUBC',1,1,4);emit('ADDC',2,2,5);loop('vector')
    branch('atan_x_positive',8);emit('SUB',2,PI,2)
    label('atan_x_positive');branch('atan_y_positive',9);emit('NEG',2,2)
    label('atan_y_positive');emit('SETSCALE',a=ZERO);ret(2,1)
    label('atan_small');fp(2,0,1,3);ret(2,2)
    for address,name in fixups:code[address]|=labels[name]
    assert len(code)<=256
    out=ROOT/'rtl/include/math_program_init.vh'
    out.write_text('// Generated by scripts/compute/microcode/build_math.py\n'+
                   '\n'.join(f"program_rom[{i}]=32'h{x:08x};" for i,x in enumerate(code))+'\n')
    (ROOT/'rtl/include/math_program_defs.vh').write_text(
        '// Generated entry addresses and opcodes.\n'+
        '\n'.join(f'localparam MP_{k.upper()}={v};' for k,v in {**OPS,**{k:labels[k] for k in ('exp','log','log_near','trig','acos','atan')}}.items())+'\n')
    (ROOT/'data/programs/math/program.lst').write_text('\n'.join(listing)+'\n')
    print(f'Math microprogram: {len(code)} x 32 bits')
if __name__=='__main__':build()
