// Generated by scripts/calibration/engine/assemble.py; edit isa.json.
`ifndef CALIB_ENGINE_DEFS_VH
`define CALIB_ENGINE_DEFS_VH
`define CE_NOP 6'h00
`define CE_END 6'h01
`define CE_MOVI 6'h02
`define CE_ADDI 6'h03
`define CE_IADD 6'h04
`define CE_ISUB 6'h05
`define CE_ICMP 6'h06
`define CE_BR 6'h07
`define CE_CALL 6'h08
`define CE_RET 6'h09
`define CE_DBNZ 6'h0a
`define CE_LD 6'h10
`define CE_ST 6'h11
`define CE_FMOV 6'h12
`define CE_LDI32 6'h13
`define CE_STI32 6'h14
`define CE_FGET32 6'h15
`define CE_FADD 6'h20
`define CE_FSUB 6'h21
`define CE_FMUL 6'h22
`define CE_FDIV 6'h23
`define CE_FSQRT 6'h24
`define CE_FCMP 6'h25
`define CE_FABS 6'h26
`define CE_FNEG 6'h27
`define CE_FCVT 6'h28
`define CE_CLASS 6'h29
`define CE_FEXP 6'h2a
`define CE_FLOG 6'h2b
`define CE_FSIN 6'h2c
`define CE_FCOS 6'h2d
`define CE_FATAN2 6'h2e
`define CE_FACOS 6'h2f
`define CE_KEXEC 6'h30
`define CE_STATUS 6'h31
`define CE_CLRFLAGS 6'h32
`define CE_HOST 6'h33
`define CE_GUARD 6'h34
`endif
