// Shared workspace capacity/layout, derived from the public configuration.
    localparam DESC=288,CURRENT=DESC+4*`PAR_ACTIVE_N,
      TRIAL=CURRENT+`PAR_STATE_N,BASELINE=TRIAL+`PAR_STATE_N,
      PLUS=BASELINE+`PAR_RESIDUALS,MINUS=PLUS+`PAR_RESIDUALS,
      COLUMN=MINUS+`PAR_RESIDUALS,JAC=COLUMN+`PAR_RESIDUALS,
      NORMAL=JAC+14*`PAR_RESIDUALS,AUGMENTED=NORMAL+`PAR_ACTIVE_N*`PAR_ACTIVE_N,
      SCALES=AUGMENTED+`PAR_GAUSS_SIZE,DELTA=SCALES+`PAR_ACTIVE_N,
      GRADIENT=DELTA+`PAR_ACTIVE_N,WORDS=1<<$clog2(GRADIENT+`PAR_ACTIVE_N);
