"""Compile detection scheduling, candidate traversal and angle search to ROM.

32-bit ISA: CALL=0 (index argument bit24, service[23:16], immediate[15:0]);
BR=1 (unconditional bit27, expected bit26, result bit[20:16], target[7:0]);
LOOP=2 (limit from result[31:16] bit24, else immediate[15:0]); NEXT=3;
END=15 (status[1:0]). Only one loop is live; loops do not nest.
The source here, not the generated words, owns detection stage order.
"""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SERVICES=dict(NATIVE=1,ORDER_OUTPUT=2,REFINE=3,MAP=4,NEXT_LAYER=5,
              FINISH=6,OUTPUT=7,DUMP=8,BOOT=9,
              CAPTURE=16,MERGE5=17,SUBPIXEL=18,MERGE3=19,RING_POINT=20,
              FILTER_FINISH=21,ORDER_CAPTURE=32,ANGLE=33,ORDER_FINISH=34,
              MINSTEP=48,HALFWIN=49,GRID_SUBPIXEL=50,VALIDATE=51,GRID_OUTPUT=52)
def build():
    words=[];listing=[];labels={};fix=[]
    def emit(w,s):listing.append(f'{len(words):03d} {w:08x} {s}');words.append(w)
    def label(s):labels[s]=len(words);listing.append(s+':')
    def call(s,index=False):emit((int(index)<<24)|(SERVICES[s]<<16),'CALL '+s+(' index' if index else ''))
    def br(s,bit=None,value=1):
        fix.append((len(words),s));emit(0x10000000|(1<<27 if bit is None else (value<<26)|(bit<<16)),'BR '+s)
    def loop(n=None):emit(0x20000000|(1<<24 if n is None else n),'LOOP '+('result.count' if n is None else str(n)))
    def nxt(s):fix.append((len(words),s));emit(0x30000000,'NEXT '+s)
    def end(n):emit(0xf0000000|n,'END '+str(n))
    call('BOOT');br('bad',0)
    label('native');call('NATIVE');call('CAPTURE');br('filter_finish',0)
    call('MERGE5');call('SUBPIXEL');call('MERGE3');br('filter_finish',1)
    loop();label('ring');call('RING_POINT',True);nxt('ring')
    label('filter_finish');call('FILTER_FINISH');call('ORDER_CAPTURE');br('order_finish',0)
    loop(90);label('angle');call('ANGLE',True);nxt('angle')
    label('order_finish');call('ORDER_FINISH');br('next_layer',0);call('ORDER_OUTPUT')
    label('refine');call('REFINE');call('MINSTEP');call('HALFWIN');call('GRID_SUBPIXEL');call('VALIDATE');call('GRID_OUTPUT')
    label('next_layer');call('NEXT_LAYER');br('finish',0);br('map',1);br('native')
    label('map');call('MAP');br('refine')
    label('finish');call('FINISH');br('none',0);call('OUTPUT');br('success',0,0);call('DUMP')
    label('success');end(1)
    label('none');end(2)
    label('bad');end(3)
    for i,s in fix:words[i]|=labels[s]
    assert len(words)<=256
    (ROOT/'rtl/include/detection_program_init.vh').write_text('// Generated by scripts/image/build_detection_program.py\n'+
        '\n'.join(f"rom[{i}]=32'h{w:08x};" for i,w in enumerate(words))+'\n')
    out=ROOT/'data/programs/detection';out.mkdir(parents=True,exist_ok=True)
    # Rebuild listing with resolved words, so branch addresses are reviewable.
    j=0;resolved=[]
    for line in listing:
        if line.endswith(':'):resolved.append(line)
        else:resolved.append(f'{j:03d} {words[j]:08x} '+line.split(' ',2)[2]);j+=1
    (out/'flow.lst').write_text('\n'.join(resolved)+'\n')
    (ROOT/'rtl/include/detection_services.vh').write_text('// Generated service IDs, include inside a module.\n'+
        '\n'.join(f"localparam DET_{k}=8'd{v};" for k,v in SERVICES.items())+'\n')
    print(f'Detection program: {len(words)} x 32 bits')
    return words,labels
if __name__=='__main__':build()
