wire [15:0] violations;
ddr_memory_model memory(.clk(clk),.rst_n(rst_n),.proto_violations(violations),
 .rd_req_valid(rd_valid),
 .rd_req_ready(rd_ready),
 .rd_req_addr(rd_addr),
 .rd_req_len_bytes(rd_len),
 .rd_req_tag(rd_tag),
 .rd_ret_valid(r_valid),
 .rd_ret_ready(r_ready),
 .rd_ret_data(r_data),
 .rd_ret_keep(r_keep),
 .rd_ret_tag(r_tag),
 .rd_ret_last(r_last),
 .rd_ret_error(r_error),
 .wr_req_valid(wr_valid),
 .wr_req_ready(wr_ready),
 .wr_req_addr(wr_addr),
 .wr_req_len_bytes(wr_len),
 .wr_req_tag(wr_tag),
 .wr_dat_valid(w_valid),
 .wr_dat_ready(w_ready),
 .wr_dat_data(w_data),
 .wr_dat_keep(w_keep),
 .wr_dat_last(w_last),
 .wr_cplt_valid(b_valid),
 .wr_cplt_ready(b_ready),
 .wr_cplt_tag(b_tag),
 .wr_cplt_error(b_error));
