wire rd_valid;
wire rd_ready;
wire [31:0] rd_addr;
wire [31:0] rd_len;
wire [15:0] rd_tag;
wire r_valid;
wire r_ready;
wire [31:0] r_data;
wire [3:0] r_keep;
wire [15:0] r_tag;
wire r_last;
wire r_error;
wire wr_valid;
wire wr_ready;
wire [31:0] wr_addr;
wire [31:0] wr_len;
wire [15:0] wr_tag;
wire w_valid;
wire w_ready;
wire [31:0] w_data;
wire [3:0] w_keep;
wire w_last;
wire b_valid;
wire b_ready;
wire [15:0] b_tag;
wire b_error;
